### ISSUE TITLE
Create GetAnalysis page

### ISSUE THREAD

**Issue by nikiburggraf** [uw-ssec/genetic-forensic-portal#16]
## Description
Given an example UUID, pull up all existing analysis by calling the APIs created in #10 #12 and #13, displaying them together on the same page

Blocked on #10 just to get an example of what this will look like. Almost everything from the commit associated with #10 could be copy/pasted to this one

## Acceptance criteria

- [ ] GetAnalysis page created
- [ ] New page/methods well-documented

**Comment by IshikaKhandelwal** [comment]
Closed here: https://github.com/uw-ssec/genetic-forensic-portal/pull/47
